export const ArrayData = [
    {
      "key": '1as',
      "first_name": "Elisa",
      "last_name": "O'Scanlon",
      "email": "eoscanlon0@printfriendly.com",
      "gender": "Female"
    }, {
      "key": '2as',
      "first_name": "Mauricio",
      "last_name": "Brecken",
      "email": "mbrecken1@google.co.uk",
      "gender": "Male"
    }, {
      "key": '3as',
      "first_name": "Melisa",
      "last_name": "MacEnelly",
      "email": "mmacenelly2@bakeyu.com",
      "gender": "Female"
    }, {
      "key": '4as',
      "first_name": "Wilek",
      "last_name": "Duxbury",
      "email": "wduxbury3@amazon.de",
      "gender": "Male"
    }, {
      "key": '5as',
      "first_name": "Demetria",
      "last_name": "Windrus",
      "email": "dwindrus4@plala.or.jp",
      "gender": "Female"
    }, {
      "key": '6as',
      "first_name": "Janeta",
      "last_name": "Carnow",
      "email": "jcarnow5@barnesandnoble.com",
      "gender": "Female"
    }, {
      "key": '7as',
      "first_name": "Norris",
      "last_name": "Easman",
      "email": "neasman6@java.com",
      "gender": "Male"
    }, {
      "key": '8as',
      "first_name": "Storm",
      "last_name": "Althorpe",
      "email": "salthorpe7@fda.gov",
      "gender": "Female"
    }, {
      "key": '9as',
      "first_name": "Nicolle",
      "last_name": "Cumesky",
      "email": "ncumesky8@csmonitor.com",
      "gender": "Female"
    }, {
      "key": '10as',
      "first_name": "Darleen",
      "last_name": "Dornin",
      "email": "ddornin9@google.es",
      "gender": "Female"
    }
  ]